# Generated by Django 2.2.6 on 2019-10-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heats',
            fields=[
                ('heat_id', models.AutoField(primary_key=True, serialize=False)),
                ('heat_finished', models.IntegerField(blank=True, null=True)),
                ('first_pass_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_pass_id', models.PositiveIntegerField(blank=True, null=True)),
                ('rtc_time_start', models.BigIntegerField()),
                ('rtc_time_end', models.BigIntegerField()),
            ],
            options={
                'db_table': 'heats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laps',
            fields=[
                ('heat_id', models.PositiveIntegerField()),
                ('pass_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('transponder_id', models.PositiveIntegerField()),
                ('rtc_time', models.BigIntegerField()),
            ],
            options={
                'db_table': 'laps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passes',
            fields=[
                ('db_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('pass_id', models.PositiveIntegerField(unique=True)),
                ('transponder_id', models.PositiveIntegerField()),
                ('rtc_time', models.BigIntegerField()),
                ('strength', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hits', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('flags', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decoder_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'passes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Karts',
            fields=[
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('kart_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('transponder_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'karts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('setting', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'settings',
                'managed': True,
            },
        ),
    ]
